dist: bionic
language: python
python:
  - 3.5
  - 3.6
  - 3.7
env:
  global:
    - PIP_INDEX_URL=https://pypi.pacificclimate.org/simple
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10-postgis-2.4
before_install:
  - export TZ=Canada/Pacific
  - pip install -U pip pytest # upgrade pytest to get pytest.approx
install:
  - pip install -r requirements.txt -r test_requirements.txt
  - pip install .
script: py.test -v --tb=short --cov --flake8 -m "not network"
